### ISSUE TITLE
Error when running execution from Maven

### ISSUE THREAD

**Issue by emmanuel-lopez** [Pi4J/pi4j-example-minimal#1]
When running the project through NetBeans12 (uses Maven 3.6.3) for execution I'd get the error.

> **Error: --module-path requires module path specification**

Fixed the issue by making the changes in pom.xml changed:

`<modulepath/>`
to
`<argument>${project.build.directory}/distribution</argument>`
in the default jar executable class section.

Didn't seem to affect the run.sh script execution. Not sure what else it might affect.

**Comment by FDelporte** [comment]
thanks @emmanuel-lopez for the feedback and fix! applied and tested OK.
